# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-26 07:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0002_song_duration'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artist',
            options={'ordering': ['name']},
        ),
        migrations.AlterUniqueTogether(
            name='song',
            unique_together=set([('title', 'artist')]),
        ),
        migrations.AlterIndexTogether(
            name='song',
            index_together=set([('title', 'artist')]),
        ),
    ]
