# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-26 07:41
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0004_remove_song_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='duration',
            field=models.DurationField(default=datetime.timedelta),
        ),
    ]
